PetAccessoriesOnlineShop/Areas/Admin/Controllers/OrderDetailController.cs
using Model.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PetAccessoriesOnlineShop.Areas.Admin.Controllers
{
    public class OrderDetailController : BaseController
    {
        // GET: Admin/OrderDetail
        public ActionResult Index(string searchString, int page = 1, int pagesize = 10)
        {
            var dao = new OrderDetailDao();
            var model = dao.ListAll(searchString, page, pagesize);
            return View(model);
        }
    }
}

PetAccessoriesOnlineShop/Areas/Admin/Views/OrderDetail/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Model.EF.OrderDetail>

@{
    ViewBag.Title = "Quản lý đơn hàng";
    Layout = "~/Areas/Admin/Views/Shared/_Layouts.cshtml";
}

@section header{
    Quản lý đơn hàng
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row">
            <div class="col-2"><span class="m-0 font-weight-bold text-primary">List OrderDetail</span> </div>
            <div class="col-5">
                @using (Html.BeginForm("Index", "OrderDetail", FormMethod.Get))
                {
                    <form class="form-inline mr-auto w-100 navbar-search">
                        <div class="input-group">
                            <input type="text" name="searchString" class="form-control  border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-success" type="submit">
                                    <i class="fas fa-search fa-sm"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                }
            </div>
        </div>

    </div>
    <div class="card-body">
        <div class="table-responsive">

            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>OrderID</th>
                        <th>ProductID</th>
                        <th>ProductName</th>
                        <th>Quantity</th>
                        <th>Price</th>
                        <th>SubTotalProduct</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr id="row_@item.Quantity">
                        <td>@item.OrderID</td>
                        <td>@item.ProductID</td>
                        <td>@item.ProductName</td>
                        <td>@item.Quantity</td>
                        <td>@item.Price</td>
                        <td>@item.SubTotalProduct</td>
                        <td>
                            <a href="/Admin/User/Edit/@item.OrderID">Edit</a>
                            |

                            @Ajax.ActionLink("Delete","Delete", new {@id = item.OrderID } ,new AjaxOptions
                       {
                           Confirm = "Are you want to delete User ?",
                           OnComplete = "('#row_"+@item.OrderID+ "').remove()",
                           HttpMethod = "Delete"

                       })

                        </td>
                    </tr>
                    }
                </tbody>
            </table>
            <div>PagedList</div>
            <th> @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))</th>

        </div>
    </div>
</div>